package com.example.dditpgrupal.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF206A4E)
val OnPrimaryLight = Color(0xFFFFFFFF)
val SecondaryLight = Color(0xFF4D6357)
val OnSecondaryLight = Color(0xFFFFFFFF)
val BackgroundLight = Color(0xFFF5FBF5)
val SurfaceLight = Color(0xFFF5FBF5)

val PrimaryDark = Color(0xFFA8F2CE)
val OnPrimaryDark = Color(0xFF003825)
val SecondaryDark = Color(0xFFB3CCBD)
val OnSecondaryDark = Color(0xFF1E352A)
val BackgroundDark = Color(0xFF171D1A)
val SurfaceDark = Color(0xFF171D1A)

val TertiaryLight = Color(0xFF3F6374)
val OnTertiaryLight = Color(0xFFFFFFFF)
val ErrorLight = Color(0xFFBA1A1A)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val SurfaceVariantLight = Color(0xFFDBE5DD)
val OnSurfaceVariantLight = Color(0xFF404943)
val OutlineLight = Color(0xFF707973)

val TertiaryDark = Color(0xFFA5CCDF)
val OnTertiaryDark = Color(0xFF073543)
val ErrorDark = Color(0xFFFFB4AB)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val SurfaceVariantDark = Color(0xFF404943)
val OnSurfaceVariantDark = Color(0xFFBFC9C2)
val OutlineDark = Color(0xFF8A938C)

val PrimaryContainerLight = Color(0xFFD0F8E4)
val OnPrimaryContainerLight = Color(0xFF002114)
val SecondaryContainerLight = Color(0xFFD0E8DB)
val OnSecondaryContainerLight = Color(0xFF0B1F16)
val TertiaryContainerLight = Color(0xFFC2E8FD)
val OnTertiaryContainerLight = Color(0xFF001F2A)
val OutlineVariantLight = Color(0xFFC0CAC2)

val PrimaryContainerDark = Color(0xFF005237)
val OnPrimaryContainerDark = Color(0xFFC3FEDF)
val SecondaryContainerDark = Color(0xFF364B40)
val OnSecondaryContainerDark = Color(0xFFCFE9DC)
val TertiaryContainerDark = Color(0xFF264B5C)
val OnTertiaryContainerDark = Color(0xFFC1E8FC)
val OutlineVariantDark = Color(0xFF404943)
